### ISSUE TITLE
Errors running base app out of the box with no changes

### ISSUE THREAD

**Issue by markkra** [bh5k/spring_mvc_base#1]
I just downloaded this repo for the Spring security video and out of the box I hit:

SEVERE: Context initialization failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [D:\dev\SpringPluralsight\spring_mvc_base\target\FitnessTracker\WEB-INF\classes\com\pluralsight\controller\GoalController.class]; nested exception is org.springframework.core.NestedIOException: ASM ClassReader failed to parse class file - probably due to a new Java class file version that isn't supported yet: file [D:\dev\SpringPluralsight\spring_mvc_base\target\FitnessTracker\WEB-INF\classes\com\pluralsight\controller\GoalController.class]; nested exception is java.lang.IllegalArgumentException

followed by a large callstack of Spring functions. I can add the entire trace but lets just start with this.

Any clues what might be missing?

Windows box. 
apache-maven-3.2.3
apache-tomcat-7.0.57
Java8

Repros in new STS install and IntelliJ IDE's plus running at the command line.

Mark

**Comment by bh5k** [comment]
My guess is that it is Java 8. In fact I am almost sure of it.

**Comment by bh5k** [comment]
It is confirmed it is because of Java 8, you can fix this one of two ways use Java 7 or change the Spring version to 4.0 inside the pom. Either is a quick easy fix.
