### ISSUE TITLE
not creating table - Spring with JPA and Hibernate

### ISSUE THREAD

**Issue by bnaoe** [bh5k/spring_mvc_base#2]
Hi I'm watching your video tutorial about Spring with JPA and Hibernate and I was trying to re-create the project from scratch. I'm sure I was able follow and understand everything in the video but when i run the program it's not even getting to this point :

Jun 28, 2015 8:24:15 PM org.apache.catalina.core.StandardContext checkUnusualURLPattern
INFO: Suspicious url pattern: "/pdfs/**" in context [/Sysmax] - see sections 12.1 and 12.2 of the Servlet specification
Jun 28, 2015 8:24:15 PM org.apache.catalina.core.StandardContext checkUnusualURLPattern
INFO: Suspicious url pattern: "/images/**" in context [/Sysmax] - see sections 12.1 and 12.2 of the Servlet specification
Jun 28, 2015 8:24:15 PM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Jun 28, 2015 8:24:16 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext

It just stops here i'm not sure what else I've missed please advise thank you:

INFO: Initializing ProtocolHandler ["http-nio-8080"]
Jun 28, 2015 8:59:47 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Jun 28, 2015 8:59:47 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["ajp-nio-8009"]
Jun 28, 2015 8:59:47 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Jun 28, 2015 8:59:47 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 876 ms
Jun 28, 2015 8:59:47 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Jun 28, 2015 8:59:47 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.0.20
Jun 28, 2015 8:59:48 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8080"]
Jun 28, 2015 8:59:48 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-nio-8009"]
Jun 28, 2015 8:59:48 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 436 ms

**Comment by bh5k** [comment]
Your configuration is not setup correctly. Try and compare it to my project configuration.
